### ISSUE TITLE
WKB from GeometryCollection is not valid?

### ISSUE THREAD

**Issue by sookoll** [geo-io/wkb-generator#1]
At least MariaDB is unable to read it. My GeometryCollection, that contains 2 points, will produce falsy WKB, so this won't work:
```
select ST_GeomCollFromWKB('00000000070000000200000000014122182780000000415911f24999999a00000000014122183a75c28f5c415911ebe8f5c28f');
```

**Comment by jsor** [comment]
You're using hex values, make sure to set the [`hex` option](https://github.com/geo-io/wkb-generator/blob/53d9b833036b6aee2450b429fb7fbb80f4243a72/src/Generator.php#L46) to false when generating the WKB.

```php
$generator = new GeoIO\WKB\Generator\Generator(
    MyExtractor(),
    [
        'hex' => false, // <- hex must be false
    ]
);
```

**Comment by sookoll** [comment]
Thanks for quick response, I followed example in README, there wasn't any documentation about it. I can't test it now, as I already moved to WKT implementation. Thanks.
